//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/JC_Express/NewInputSystem_Template/ControlMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlMap"",
    ""maps"": [
        {
            ""name"": ""PlayerInput"",
            ""id"": ""5817de3f-064b-4d9e-8120-cc5ccfb40ddf"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""46884a52-6acb-4025-b136-a743d0a4b760"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c95b4513-e61b-4bdd-937e-0e6d0de3215a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1135c4ad-23af-4826-b715-ce0c9be0ceeb"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a725d732-b761-48a9-97f3-377ff2303eb7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""43021451-ba3f-40d4-9e7c-955c81219411"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""104a37da-bf59-4fdf-80a9-59b6bd491b3b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Petroller"",
            ""id"": ""a4a41900-a733-48cd-8889-72838548932a"",
            ""actions"": [
                {
                    ""name"": ""Pull"",
                    ""type"": ""Value"",
                    ""id"": ""d0da2ba3-b422-4ad2-882d-c9b8146b0e93"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""VerticalPress"",
                    ""type"": ""Button"",
                    ""id"": ""161fdf33-2889-49b6-882a-26226d5bf8a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HorizontalPress"",
                    ""type"": ""Button"",
                    ""id"": ""95f10703-6eaf-4a08-ad7a-90761a6e75a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pos"",
                    ""type"": ""Value"",
                    ""id"": ""198cd316-34bf-4e03-a086-05e61718ac70"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rot"",
                    ""type"": ""Value"",
                    ""id"": ""25085b45-5e54-4598-8278-bce7941a7e78"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeviceVelocity"",
                    ""type"": ""Value"",
                    ""id"": ""90eacbe6-65a4-44a0-8c19-45864f0e8923"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeviceAngularVelocity"",
                    ""type"": ""Value"",
                    ""id"": ""fc7fe55f-386d-4bda-81ed-8637ed9b5f71"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeviceAcceleration"",
                    ""type"": ""Value"",
                    ""id"": ""237bbc40-d2e9-4b3d-9a6a-b5790bfc081a"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeviceAugularAcceleration"",
                    ""type"": ""Value"",
                    ""id"": ""5ef3ca71-6b5f-4775-b32c-276b0a1ee6e6"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2eafe30b-94b4-4976-9293-296f3f503351"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd7c72fd-bfc1-43c3-9db1-3d9105d55c88"",
                    ""path"": ""<XRController>{RightHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a709e6f-4b32-4453-a9a7-a92d3b9e5586"",
                    ""path"": ""<XRController>{RightHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3e3d842-02f7-40c6-af9a-7310c0ca9ca8"",
                    ""path"": ""<XRController>{RightHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c5a37f9-97d1-4f63-9c64-70693083a955"",
                    ""path"": ""<XRController>{RightHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f44ea030-83a8-4346-800b-9a12a1b25eb6"",
                    ""path"": ""<XRController>{RightHand}/deviceVelocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4274467f-1163-4801-bea9-808651b504d7"",
                    ""path"": ""<XRController>{RightHand}/deviceAngularVelocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceAngularVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4450fd98-01b6-428d-bfe9-a3111a408c60"",
                    ""path"": ""<XRController>{RightHand}/deviceAcceleration"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceAcceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ab0b91a-30ea-445f-8d1d-c0c926cc89f1"",
                    ""path"": ""<XRController>{RightHand}/deviceAngularAcceleration"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceAugularAcceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Prototype"",
            ""id"": ""89bfc611-2c5b-44b2-89e7-95148a8c8489"",
            ""actions"": [
                {
                    ""name"": ""Right_Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""11971646-e56e-4c21-982d-8fef2033129a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left_Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""4797e0bc-d639-48ad-bdc0-701e7be189e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right_Grip"",
                    ""type"": ""Button"",
                    ""id"": ""e9b31bc8-f6bc-4388-8077-83d74cc8c6d0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left_Grip"",
                    ""type"": ""Button"",
                    ""id"": ""ab1f5d8a-2e9b-478f-a382-5bb4a88237c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RJoystick"",
                    ""type"": ""Value"",
                    ""id"": ""3e908f4e-d8ab-4aa5-a2a2-65189ffa59cd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LJoystick"",
                    ""type"": ""Value"",
                    ""id"": ""ee0f1d77-81b7-43dd-8ed9-00cc3a2c44e0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LHandToggle"",
                    ""type"": ""Button"",
                    ""id"": ""4fbea772-7baf-4349-b7d6-0c716e988df7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTouchToggle"",
                    ""type"": ""Button"",
                    ""id"": ""c51459a7-e27f-4458-9959-79989e9fe568"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RHandToggle"",
                    ""type"": ""Button"",
                    ""id"": ""ea7939f3-ea19-4c7b-b28e-d39d484b4ee8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RTouchToggle"",
                    ""type"": ""Button"",
                    ""id"": ""14bc0cf7-30e1-4b45-9314-81af5923c51a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RecordButton"",
                    ""type"": ""Button"",
                    ""id"": ""416b8150-1076-4c07-9f0f-4db042d908c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaceInfoBoard"",
                    ""type"": ""Button"",
                    ""id"": ""c7dbe4b6-44c8-4ada-bba0-ecaad32d574b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SettingsToggle"",
                    ""type"": ""Button"",
                    ""id"": ""9a39854a-8de6-4307-9138-d2a7ef1e6c28"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Any_Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""b10ea3d5-c421-4ae2-9466-8bbfbde186ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Any_Grip"",
                    ""type"": ""Button"",
                    ""id"": ""5810380f-3acf-4bb4-af0d-ac832ebf9a0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""X"",
                    ""type"": ""Button"",
                    ""id"": ""745c348f-e598-47b1-8bb0-0dd1930d3653"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y"",
                    ""type"": ""Button"",
                    ""id"": ""f6a4fb48-e1c0-4a9c-901c-358e472cf00c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""7eea4310-d2fc-4780-b7d2-32a5973179af"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B"",
                    ""type"": ""Button"",
                    ""id"": ""86ccb5a5-81db-4c4d-8899-76a4ff7147dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Record"",
                    ""type"": ""Button"",
                    ""id"": ""05c74f30-7fc4-4dbd-9b5b-ee3599ac789b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Delete"",
                    ""type"": ""Button"",
                    ""id"": ""d1089613-53c6-41c6-99f8-df08e433eedf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReCenter"",
                    ""type"": ""Button"",
                    ""id"": ""880329ac-af10-45f0-b4eb-e1b4aa683dd1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""PassThrough"",
                    ""id"": ""fe40c30f-f8ac-488f-ac0d-ef6b57bcaa39"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MasterControl"",
                    ""type"": ""Button"",
                    ""id"": ""8ccd16bd-1c1c-43e5-9c92-649a2d8252b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""92c0048e-4aed-4b02-b433-ae03806b12bf"",
                    ""path"": ""<XRController>{RightHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d37da738-d96c-4302-a85e-1ebe8850c188"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1a7a4b8-9a4a-45bf-9f12-59292460496f"",
                    ""path"": ""<XRController>{RightHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""84ef9bd4-bccd-43b7-8e41-d413645dd3ed"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LHandToggle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e6e98b7e-f6c7-498b-9383-81d71d2b9477"",
                    ""path"": ""<XRController>{LeftHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LHandToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""853e619c-47d0-4f42-98f7-c1c71c6a0eb4"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LHandToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""ab405f31-53a9-412d-9c7c-b24170f8d994"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RHandToggle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""d5106873-b746-43d9-979c-f10bbe2ad6bc"",
                    ""path"": ""<XRController>{RightHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RHandToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""ad8f6e96-bd20-423f-b9cc-944f0b848850"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RHandToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""2dde93ab-9850-4026-9031-97a2b1c8d6a2"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecordButton"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""346b1ec8-bf1f-4224-9859-7625920bd869"",
                    ""path"": ""<XRController>{LeftHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecordButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""29032b52-6a25-44d4-8d73-56fda3d8c5e3"",
                    ""path"": ""<XRController>{LeftHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecordButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""146dfbe9-5053-4a49-9908-3ea43ec0e03b"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecordButton"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""06c3f798-d124-4f42-a479-0eaa5a80b20f"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecordButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""51477af7-f25d-438b-8299-da1c3d8bcf19"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecordButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""cd0d16c1-3f00-47b7-b122-da836b5263dc"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceInfoBoard"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""2cb267f5-edf9-4a35-9872-bfda0aa48b2f"",
                    ""path"": ""<XRController>{LeftHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceInfoBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0881e817-fd75-4a20-a4de-3a1208f0686d"",
                    ""path"": ""<XRController>{RightHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceInfoBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""53182053-a9c7-49ec-b212-e69eb38f81b8"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTouchToggle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""5ea54911-cc39-4f3b-a007-bca0be8b432f"",
                    ""path"": ""<XRController>{LeftHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTouchToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""a13b645b-b709-4c36-a20a-136b43c633b1"",
                    ""path"": ""<XRController>{LeftHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTouchToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""cde826fa-4549-457e-a645-5e0067c953e5"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTouchToggle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""32250884-a0a4-45f7-afa0-6548af24aff4"",
                    ""path"": ""<XRController>{RightHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTouchToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""7f1ac7b7-679e-468b-a1b0-8bec4deb68c8"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTouchToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""34b821e2-15c1-4dc7-b504-ac2b6f340402"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SettingsToggle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""eb5ba9eb-cdfd-4282-adda-652f67535ebc"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SettingsToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""cd9614a2-a238-4bd5-a368-6a73fa4b75f5"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SettingsToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5b3e37dd-0b65-4d5d-ba85-4dab16712e90"",
                    ""path"": ""<XRController>{LeftHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left_Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82f87eea-1998-4424-83f1-d16103e9ff46"",
                    ""path"": ""<XRController>{LeftHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left_Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72367e93-d9c2-4c9b-8da3-ca029d34e13b"",
                    ""path"": ""<XRController>{LeftHand}/primary2DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""143ad251-106c-4ffa-b785-627d68f2a070"",
                    ""path"": ""<XRController>{RightHand}/primary2DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b07f6d6-ea68-4a52-929c-afb8967230ee"",
                    ""path"": ""<XRController>/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Any_Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d1efa47-dde2-4f6c-84ed-04ddb7b0f26a"",
                    ""path"": ""<XRController>/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Any_Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2d21c8f-1535-40b7-9dc8-7ed2f661dd2e"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0a345a9-b301-4ba5-a762-0c7b7729dfbf"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7618d802-8189-4efd-b8f9-9b25e0ccc0f9"",
                    ""path"": ""<XRController>{LeftHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eade8d0d-f2f6-48fb-852a-da72c9a0be53"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7fe731b-d940-43fa-a5ac-800403d5602f"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97a82cb4-c767-4e89-81d7-93769c1518a1"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""437fe4c5-8de5-4381-9ac5-6652134a10b2"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdc40677-b44b-4eb6-a13e-89fa8c8e45db"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""78101b78-f1ef-461b-b527-b0cfa07d0522"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Record"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""12d8fc7d-a2af-4463-b3a4-09b580811f84"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Record"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""cffa4cbd-3649-42a8-b338-bc6097e7e492"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Record"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""dd8a28b5-faa4-4ac3-88d9-f938d1e0a664"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Record"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7c631110-dab9-415e-bbaf-fe9f645e1175"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Record"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""afb666b4-9e1d-4144-b5de-6dc4230c31d1"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Record"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""56c15013-dc2e-4ca6-bfbc-f1a877339bc5"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""0f7b43a3-ebd3-4a74-8963-400ba08e743a"",
                    ""path"": ""<XRController>{LeftHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""d0839274-cce9-47ee-adbe-dffec798b802"",
                    ""path"": ""*/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""c7921917-8b65-4860-9c0c-0f84e1be93b3"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ca0d116a-2668-4a64-a4fe-d357cecaadb4"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""fb234455-f736-464f-8abf-6f590a4726cb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""5393096e-cec0-44ab-b6d2-12f8aa0fdbbd"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReCenter"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""cd3f89f6-eca1-4136-852d-a3450f22e035"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReCenter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""8458f667-83f5-4f06-a960-061a6be284f1"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReCenter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9af1a97c-d112-4ea9-9868-17d3c2e73c2c"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""f55f3304-ae85-4768-8b21-84f92f1dd621"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MasterControl"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""e8e95fc7-2621-46df-838a-e56b87c93908"",
                    ""path"": ""<XRController>{LeftHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MasterControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""7c36eace-d758-4af9-91f4-c504879ebd04"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MasterControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""9d129809-4e00-4140-bfb1-03e4e77d89d1"",
                    ""path"": ""<XRController>{LeftHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MasterControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInput
        m_PlayerInput = asset.FindActionMap("PlayerInput", throwIfNotFound: true);
        m_PlayerInput_Move = m_PlayerInput.FindAction("Move", throwIfNotFound: true);
        // Petroller
        m_Petroller = asset.FindActionMap("Petroller", throwIfNotFound: true);
        m_Petroller_Pull = m_Petroller.FindAction("Pull", throwIfNotFound: true);
        m_Petroller_VerticalPress = m_Petroller.FindAction("VerticalPress", throwIfNotFound: true);
        m_Petroller_HorizontalPress = m_Petroller.FindAction("HorizontalPress", throwIfNotFound: true);
        m_Petroller_Pos = m_Petroller.FindAction("Pos", throwIfNotFound: true);
        m_Petroller_Rot = m_Petroller.FindAction("Rot", throwIfNotFound: true);
        m_Petroller_DeviceVelocity = m_Petroller.FindAction("DeviceVelocity", throwIfNotFound: true);
        m_Petroller_DeviceAngularVelocity = m_Petroller.FindAction("DeviceAngularVelocity", throwIfNotFound: true);
        m_Petroller_DeviceAcceleration = m_Petroller.FindAction("DeviceAcceleration", throwIfNotFound: true);
        m_Petroller_DeviceAugularAcceleration = m_Petroller.FindAction("DeviceAugularAcceleration", throwIfNotFound: true);
        // Prototype
        m_Prototype = asset.FindActionMap("Prototype", throwIfNotFound: true);
        m_Prototype_Right_Trigger = m_Prototype.FindAction("Right_Trigger", throwIfNotFound: true);
        m_Prototype_Left_Trigger = m_Prototype.FindAction("Left_Trigger", throwIfNotFound: true);
        m_Prototype_Right_Grip = m_Prototype.FindAction("Right_Grip", throwIfNotFound: true);
        m_Prototype_Left_Grip = m_Prototype.FindAction("Left_Grip", throwIfNotFound: true);
        m_Prototype_RJoystick = m_Prototype.FindAction("RJoystick", throwIfNotFound: true);
        m_Prototype_LJoystick = m_Prototype.FindAction("LJoystick", throwIfNotFound: true);
        m_Prototype_LHandToggle = m_Prototype.FindAction("LHandToggle", throwIfNotFound: true);
        m_Prototype_LTouchToggle = m_Prototype.FindAction("LTouchToggle", throwIfNotFound: true);
        m_Prototype_RHandToggle = m_Prototype.FindAction("RHandToggle", throwIfNotFound: true);
        m_Prototype_RTouchToggle = m_Prototype.FindAction("RTouchToggle", throwIfNotFound: true);
        m_Prototype_RecordButton = m_Prototype.FindAction("RecordButton", throwIfNotFound: true);
        m_Prototype_PlaceInfoBoard = m_Prototype.FindAction("PlaceInfoBoard", throwIfNotFound: true);
        m_Prototype_SettingsToggle = m_Prototype.FindAction("SettingsToggle", throwIfNotFound: true);
        m_Prototype_Any_Trigger = m_Prototype.FindAction("Any_Trigger", throwIfNotFound: true);
        m_Prototype_Any_Grip = m_Prototype.FindAction("Any_Grip", throwIfNotFound: true);
        m_Prototype_X = m_Prototype.FindAction("X", throwIfNotFound: true);
        m_Prototype_Y = m_Prototype.FindAction("Y", throwIfNotFound: true);
        m_Prototype_A = m_Prototype.FindAction("A", throwIfNotFound: true);
        m_Prototype_B = m_Prototype.FindAction("B", throwIfNotFound: true);
        m_Prototype_Record = m_Prototype.FindAction("Record", throwIfNotFound: true);
        m_Prototype_Delete = m_Prototype.FindAction("Delete", throwIfNotFound: true);
        m_Prototype_ReCenter = m_Prototype.FindAction("ReCenter", throwIfNotFound: true);
        m_Prototype_Zoom = m_Prototype.FindAction("Zoom", throwIfNotFound: true);
        m_Prototype_MasterControl = m_Prototype.FindAction("MasterControl", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInput
    private readonly InputActionMap m_PlayerInput;
    private List<IPlayerInputActions> m_PlayerInputActionsCallbackInterfaces = new List<IPlayerInputActions>();
    private readonly InputAction m_PlayerInput_Move;
    public struct PlayerInputActions
    {
        private @ControlMap m_Wrapper;
        public PlayerInputActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerInput_Move;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IPlayerInputActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IPlayerInputActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerInputActions @PlayerInput => new PlayerInputActions(this);

    // Petroller
    private readonly InputActionMap m_Petroller;
    private List<IPetrollerActions> m_PetrollerActionsCallbackInterfaces = new List<IPetrollerActions>();
    private readonly InputAction m_Petroller_Pull;
    private readonly InputAction m_Petroller_VerticalPress;
    private readonly InputAction m_Petroller_HorizontalPress;
    private readonly InputAction m_Petroller_Pos;
    private readonly InputAction m_Petroller_Rot;
    private readonly InputAction m_Petroller_DeviceVelocity;
    private readonly InputAction m_Petroller_DeviceAngularVelocity;
    private readonly InputAction m_Petroller_DeviceAcceleration;
    private readonly InputAction m_Petroller_DeviceAugularAcceleration;
    public struct PetrollerActions
    {
        private @ControlMap m_Wrapper;
        public PetrollerActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pull => m_Wrapper.m_Petroller_Pull;
        public InputAction @VerticalPress => m_Wrapper.m_Petroller_VerticalPress;
        public InputAction @HorizontalPress => m_Wrapper.m_Petroller_HorizontalPress;
        public InputAction @Pos => m_Wrapper.m_Petroller_Pos;
        public InputAction @Rot => m_Wrapper.m_Petroller_Rot;
        public InputAction @DeviceVelocity => m_Wrapper.m_Petroller_DeviceVelocity;
        public InputAction @DeviceAngularVelocity => m_Wrapper.m_Petroller_DeviceAngularVelocity;
        public InputAction @DeviceAcceleration => m_Wrapper.m_Petroller_DeviceAcceleration;
        public InputAction @DeviceAugularAcceleration => m_Wrapper.m_Petroller_DeviceAugularAcceleration;
        public InputActionMap Get() { return m_Wrapper.m_Petroller; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PetrollerActions set) { return set.Get(); }
        public void AddCallbacks(IPetrollerActions instance)
        {
            if (instance == null || m_Wrapper.m_PetrollerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PetrollerActionsCallbackInterfaces.Add(instance);
            @Pull.started += instance.OnPull;
            @Pull.performed += instance.OnPull;
            @Pull.canceled += instance.OnPull;
            @VerticalPress.started += instance.OnVerticalPress;
            @VerticalPress.performed += instance.OnVerticalPress;
            @VerticalPress.canceled += instance.OnVerticalPress;
            @HorizontalPress.started += instance.OnHorizontalPress;
            @HorizontalPress.performed += instance.OnHorizontalPress;
            @HorizontalPress.canceled += instance.OnHorizontalPress;
            @Pos.started += instance.OnPos;
            @Pos.performed += instance.OnPos;
            @Pos.canceled += instance.OnPos;
            @Rot.started += instance.OnRot;
            @Rot.performed += instance.OnRot;
            @Rot.canceled += instance.OnRot;
            @DeviceVelocity.started += instance.OnDeviceVelocity;
            @DeviceVelocity.performed += instance.OnDeviceVelocity;
            @DeviceVelocity.canceled += instance.OnDeviceVelocity;
            @DeviceAngularVelocity.started += instance.OnDeviceAngularVelocity;
            @DeviceAngularVelocity.performed += instance.OnDeviceAngularVelocity;
            @DeviceAngularVelocity.canceled += instance.OnDeviceAngularVelocity;
            @DeviceAcceleration.started += instance.OnDeviceAcceleration;
            @DeviceAcceleration.performed += instance.OnDeviceAcceleration;
            @DeviceAcceleration.canceled += instance.OnDeviceAcceleration;
            @DeviceAugularAcceleration.started += instance.OnDeviceAugularAcceleration;
            @DeviceAugularAcceleration.performed += instance.OnDeviceAugularAcceleration;
            @DeviceAugularAcceleration.canceled += instance.OnDeviceAugularAcceleration;
        }

        private void UnregisterCallbacks(IPetrollerActions instance)
        {
            @Pull.started -= instance.OnPull;
            @Pull.performed -= instance.OnPull;
            @Pull.canceled -= instance.OnPull;
            @VerticalPress.started -= instance.OnVerticalPress;
            @VerticalPress.performed -= instance.OnVerticalPress;
            @VerticalPress.canceled -= instance.OnVerticalPress;
            @HorizontalPress.started -= instance.OnHorizontalPress;
            @HorizontalPress.performed -= instance.OnHorizontalPress;
            @HorizontalPress.canceled -= instance.OnHorizontalPress;
            @Pos.started -= instance.OnPos;
            @Pos.performed -= instance.OnPos;
            @Pos.canceled -= instance.OnPos;
            @Rot.started -= instance.OnRot;
            @Rot.performed -= instance.OnRot;
            @Rot.canceled -= instance.OnRot;
            @DeviceVelocity.started -= instance.OnDeviceVelocity;
            @DeviceVelocity.performed -= instance.OnDeviceVelocity;
            @DeviceVelocity.canceled -= instance.OnDeviceVelocity;
            @DeviceAngularVelocity.started -= instance.OnDeviceAngularVelocity;
            @DeviceAngularVelocity.performed -= instance.OnDeviceAngularVelocity;
            @DeviceAngularVelocity.canceled -= instance.OnDeviceAngularVelocity;
            @DeviceAcceleration.started -= instance.OnDeviceAcceleration;
            @DeviceAcceleration.performed -= instance.OnDeviceAcceleration;
            @DeviceAcceleration.canceled -= instance.OnDeviceAcceleration;
            @DeviceAugularAcceleration.started -= instance.OnDeviceAugularAcceleration;
            @DeviceAugularAcceleration.performed -= instance.OnDeviceAugularAcceleration;
            @DeviceAugularAcceleration.canceled -= instance.OnDeviceAugularAcceleration;
        }

        public void RemoveCallbacks(IPetrollerActions instance)
        {
            if (m_Wrapper.m_PetrollerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPetrollerActions instance)
        {
            foreach (var item in m_Wrapper.m_PetrollerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PetrollerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PetrollerActions @Petroller => new PetrollerActions(this);

    // Prototype
    private readonly InputActionMap m_Prototype;
    private List<IPrototypeActions> m_PrototypeActionsCallbackInterfaces = new List<IPrototypeActions>();
    private readonly InputAction m_Prototype_Right_Trigger;
    private readonly InputAction m_Prototype_Left_Trigger;
    private readonly InputAction m_Prototype_Right_Grip;
    private readonly InputAction m_Prototype_Left_Grip;
    private readonly InputAction m_Prototype_RJoystick;
    private readonly InputAction m_Prototype_LJoystick;
    private readonly InputAction m_Prototype_LHandToggle;
    private readonly InputAction m_Prototype_LTouchToggle;
    private readonly InputAction m_Prototype_RHandToggle;
    private readonly InputAction m_Prototype_RTouchToggle;
    private readonly InputAction m_Prototype_RecordButton;
    private readonly InputAction m_Prototype_PlaceInfoBoard;
    private readonly InputAction m_Prototype_SettingsToggle;
    private readonly InputAction m_Prototype_Any_Trigger;
    private readonly InputAction m_Prototype_Any_Grip;
    private readonly InputAction m_Prototype_X;
    private readonly InputAction m_Prototype_Y;
    private readonly InputAction m_Prototype_A;
    private readonly InputAction m_Prototype_B;
    private readonly InputAction m_Prototype_Record;
    private readonly InputAction m_Prototype_Delete;
    private readonly InputAction m_Prototype_ReCenter;
    private readonly InputAction m_Prototype_Zoom;
    private readonly InputAction m_Prototype_MasterControl;
    public struct PrototypeActions
    {
        private @ControlMap m_Wrapper;
        public PrototypeActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Right_Trigger => m_Wrapper.m_Prototype_Right_Trigger;
        public InputAction @Left_Trigger => m_Wrapper.m_Prototype_Left_Trigger;
        public InputAction @Right_Grip => m_Wrapper.m_Prototype_Right_Grip;
        public InputAction @Left_Grip => m_Wrapper.m_Prototype_Left_Grip;
        public InputAction @RJoystick => m_Wrapper.m_Prototype_RJoystick;
        public InputAction @LJoystick => m_Wrapper.m_Prototype_LJoystick;
        public InputAction @LHandToggle => m_Wrapper.m_Prototype_LHandToggle;
        public InputAction @LTouchToggle => m_Wrapper.m_Prototype_LTouchToggle;
        public InputAction @RHandToggle => m_Wrapper.m_Prototype_RHandToggle;
        public InputAction @RTouchToggle => m_Wrapper.m_Prototype_RTouchToggle;
        public InputAction @RecordButton => m_Wrapper.m_Prototype_RecordButton;
        public InputAction @PlaceInfoBoard => m_Wrapper.m_Prototype_PlaceInfoBoard;
        public InputAction @SettingsToggle => m_Wrapper.m_Prototype_SettingsToggle;
        public InputAction @Any_Trigger => m_Wrapper.m_Prototype_Any_Trigger;
        public InputAction @Any_Grip => m_Wrapper.m_Prototype_Any_Grip;
        public InputAction @X => m_Wrapper.m_Prototype_X;
        public InputAction @Y => m_Wrapper.m_Prototype_Y;
        public InputAction @A => m_Wrapper.m_Prototype_A;
        public InputAction @B => m_Wrapper.m_Prototype_B;
        public InputAction @Record => m_Wrapper.m_Prototype_Record;
        public InputAction @Delete => m_Wrapper.m_Prototype_Delete;
        public InputAction @ReCenter => m_Wrapper.m_Prototype_ReCenter;
        public InputAction @Zoom => m_Wrapper.m_Prototype_Zoom;
        public InputAction @MasterControl => m_Wrapper.m_Prototype_MasterControl;
        public InputActionMap Get() { return m_Wrapper.m_Prototype; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PrototypeActions set) { return set.Get(); }
        public void AddCallbacks(IPrototypeActions instance)
        {
            if (instance == null || m_Wrapper.m_PrototypeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PrototypeActionsCallbackInterfaces.Add(instance);
            @Right_Trigger.started += instance.OnRight_Trigger;
            @Right_Trigger.performed += instance.OnRight_Trigger;
            @Right_Trigger.canceled += instance.OnRight_Trigger;
            @Left_Trigger.started += instance.OnLeft_Trigger;
            @Left_Trigger.performed += instance.OnLeft_Trigger;
            @Left_Trigger.canceled += instance.OnLeft_Trigger;
            @Right_Grip.started += instance.OnRight_Grip;
            @Right_Grip.performed += instance.OnRight_Grip;
            @Right_Grip.canceled += instance.OnRight_Grip;
            @Left_Grip.started += instance.OnLeft_Grip;
            @Left_Grip.performed += instance.OnLeft_Grip;
            @Left_Grip.canceled += instance.OnLeft_Grip;
            @RJoystick.started += instance.OnRJoystick;
            @RJoystick.performed += instance.OnRJoystick;
            @RJoystick.canceled += instance.OnRJoystick;
            @LJoystick.started += instance.OnLJoystick;
            @LJoystick.performed += instance.OnLJoystick;
            @LJoystick.canceled += instance.OnLJoystick;
            @LHandToggle.started += instance.OnLHandToggle;
            @LHandToggle.performed += instance.OnLHandToggle;
            @LHandToggle.canceled += instance.OnLHandToggle;
            @LTouchToggle.started += instance.OnLTouchToggle;
            @LTouchToggle.performed += instance.OnLTouchToggle;
            @LTouchToggle.canceled += instance.OnLTouchToggle;
            @RHandToggle.started += instance.OnRHandToggle;
            @RHandToggle.performed += instance.OnRHandToggle;
            @RHandToggle.canceled += instance.OnRHandToggle;
            @RTouchToggle.started += instance.OnRTouchToggle;
            @RTouchToggle.performed += instance.OnRTouchToggle;
            @RTouchToggle.canceled += instance.OnRTouchToggle;
            @RecordButton.started += instance.OnRecordButton;
            @RecordButton.performed += instance.OnRecordButton;
            @RecordButton.canceled += instance.OnRecordButton;
            @PlaceInfoBoard.started += instance.OnPlaceInfoBoard;
            @PlaceInfoBoard.performed += instance.OnPlaceInfoBoard;
            @PlaceInfoBoard.canceled += instance.OnPlaceInfoBoard;
            @SettingsToggle.started += instance.OnSettingsToggle;
            @SettingsToggle.performed += instance.OnSettingsToggle;
            @SettingsToggle.canceled += instance.OnSettingsToggle;
            @Any_Trigger.started += instance.OnAny_Trigger;
            @Any_Trigger.performed += instance.OnAny_Trigger;
            @Any_Trigger.canceled += instance.OnAny_Trigger;
            @Any_Grip.started += instance.OnAny_Grip;
            @Any_Grip.performed += instance.OnAny_Grip;
            @Any_Grip.canceled += instance.OnAny_Grip;
            @X.started += instance.OnX;
            @X.performed += instance.OnX;
            @X.canceled += instance.OnX;
            @Y.started += instance.OnY;
            @Y.performed += instance.OnY;
            @Y.canceled += instance.OnY;
            @A.started += instance.OnA;
            @A.performed += instance.OnA;
            @A.canceled += instance.OnA;
            @B.started += instance.OnB;
            @B.performed += instance.OnB;
            @B.canceled += instance.OnB;
            @Record.started += instance.OnRecord;
            @Record.performed += instance.OnRecord;
            @Record.canceled += instance.OnRecord;
            @Delete.started += instance.OnDelete;
            @Delete.performed += instance.OnDelete;
            @Delete.canceled += instance.OnDelete;
            @ReCenter.started += instance.OnReCenter;
            @ReCenter.performed += instance.OnReCenter;
            @ReCenter.canceled += instance.OnReCenter;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
            @MasterControl.started += instance.OnMasterControl;
            @MasterControl.performed += instance.OnMasterControl;
            @MasterControl.canceled += instance.OnMasterControl;
        }

        private void UnregisterCallbacks(IPrototypeActions instance)
        {
            @Right_Trigger.started -= instance.OnRight_Trigger;
            @Right_Trigger.performed -= instance.OnRight_Trigger;
            @Right_Trigger.canceled -= instance.OnRight_Trigger;
            @Left_Trigger.started -= instance.OnLeft_Trigger;
            @Left_Trigger.performed -= instance.OnLeft_Trigger;
            @Left_Trigger.canceled -= instance.OnLeft_Trigger;
            @Right_Grip.started -= instance.OnRight_Grip;
            @Right_Grip.performed -= instance.OnRight_Grip;
            @Right_Grip.canceled -= instance.OnRight_Grip;
            @Left_Grip.started -= instance.OnLeft_Grip;
            @Left_Grip.performed -= instance.OnLeft_Grip;
            @Left_Grip.canceled -= instance.OnLeft_Grip;
            @RJoystick.started -= instance.OnRJoystick;
            @RJoystick.performed -= instance.OnRJoystick;
            @RJoystick.canceled -= instance.OnRJoystick;
            @LJoystick.started -= instance.OnLJoystick;
            @LJoystick.performed -= instance.OnLJoystick;
            @LJoystick.canceled -= instance.OnLJoystick;
            @LHandToggle.started -= instance.OnLHandToggle;
            @LHandToggle.performed -= instance.OnLHandToggle;
            @LHandToggle.canceled -= instance.OnLHandToggle;
            @LTouchToggle.started -= instance.OnLTouchToggle;
            @LTouchToggle.performed -= instance.OnLTouchToggle;
            @LTouchToggle.canceled -= instance.OnLTouchToggle;
            @RHandToggle.started -= instance.OnRHandToggle;
            @RHandToggle.performed -= instance.OnRHandToggle;
            @RHandToggle.canceled -= instance.OnRHandToggle;
            @RTouchToggle.started -= instance.OnRTouchToggle;
            @RTouchToggle.performed -= instance.OnRTouchToggle;
            @RTouchToggle.canceled -= instance.OnRTouchToggle;
            @RecordButton.started -= instance.OnRecordButton;
            @RecordButton.performed -= instance.OnRecordButton;
            @RecordButton.canceled -= instance.OnRecordButton;
            @PlaceInfoBoard.started -= instance.OnPlaceInfoBoard;
            @PlaceInfoBoard.performed -= instance.OnPlaceInfoBoard;
            @PlaceInfoBoard.canceled -= instance.OnPlaceInfoBoard;
            @SettingsToggle.started -= instance.OnSettingsToggle;
            @SettingsToggle.performed -= instance.OnSettingsToggle;
            @SettingsToggle.canceled -= instance.OnSettingsToggle;
            @Any_Trigger.started -= instance.OnAny_Trigger;
            @Any_Trigger.performed -= instance.OnAny_Trigger;
            @Any_Trigger.canceled -= instance.OnAny_Trigger;
            @Any_Grip.started -= instance.OnAny_Grip;
            @Any_Grip.performed -= instance.OnAny_Grip;
            @Any_Grip.canceled -= instance.OnAny_Grip;
            @X.started -= instance.OnX;
            @X.performed -= instance.OnX;
            @X.canceled -= instance.OnX;
            @Y.started -= instance.OnY;
            @Y.performed -= instance.OnY;
            @Y.canceled -= instance.OnY;
            @A.started -= instance.OnA;
            @A.performed -= instance.OnA;
            @A.canceled -= instance.OnA;
            @B.started -= instance.OnB;
            @B.performed -= instance.OnB;
            @B.canceled -= instance.OnB;
            @Record.started -= instance.OnRecord;
            @Record.performed -= instance.OnRecord;
            @Record.canceled -= instance.OnRecord;
            @Delete.started -= instance.OnDelete;
            @Delete.performed -= instance.OnDelete;
            @Delete.canceled -= instance.OnDelete;
            @ReCenter.started -= instance.OnReCenter;
            @ReCenter.performed -= instance.OnReCenter;
            @ReCenter.canceled -= instance.OnReCenter;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
            @MasterControl.started -= instance.OnMasterControl;
            @MasterControl.performed -= instance.OnMasterControl;
            @MasterControl.canceled -= instance.OnMasterControl;
        }

        public void RemoveCallbacks(IPrototypeActions instance)
        {
            if (m_Wrapper.m_PrototypeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPrototypeActions instance)
        {
            foreach (var item in m_Wrapper.m_PrototypeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PrototypeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PrototypeActions @Prototype => new PrototypeActions(this);
    public interface IPlayerInputActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IPetrollerActions
    {
        void OnPull(InputAction.CallbackContext context);
        void OnVerticalPress(InputAction.CallbackContext context);
        void OnHorizontalPress(InputAction.CallbackContext context);
        void OnPos(InputAction.CallbackContext context);
        void OnRot(InputAction.CallbackContext context);
        void OnDeviceVelocity(InputAction.CallbackContext context);
        void OnDeviceAngularVelocity(InputAction.CallbackContext context);
        void OnDeviceAcceleration(InputAction.CallbackContext context);
        void OnDeviceAugularAcceleration(InputAction.CallbackContext context);
    }
    public interface IPrototypeActions
    {
        void OnRight_Trigger(InputAction.CallbackContext context);
        void OnLeft_Trigger(InputAction.CallbackContext context);
        void OnRight_Grip(InputAction.CallbackContext context);
        void OnLeft_Grip(InputAction.CallbackContext context);
        void OnRJoystick(InputAction.CallbackContext context);
        void OnLJoystick(InputAction.CallbackContext context);
        void OnLHandToggle(InputAction.CallbackContext context);
        void OnLTouchToggle(InputAction.CallbackContext context);
        void OnRHandToggle(InputAction.CallbackContext context);
        void OnRTouchToggle(InputAction.CallbackContext context);
        void OnRecordButton(InputAction.CallbackContext context);
        void OnPlaceInfoBoard(InputAction.CallbackContext context);
        void OnSettingsToggle(InputAction.CallbackContext context);
        void OnAny_Trigger(InputAction.CallbackContext context);
        void OnAny_Grip(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnY(InputAction.CallbackContext context);
        void OnA(InputAction.CallbackContext context);
        void OnB(InputAction.CallbackContext context);
        void OnRecord(InputAction.CallbackContext context);
        void OnDelete(InputAction.CallbackContext context);
        void OnReCenter(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnMasterControl(InputAction.CallbackContext context);
    }
}
