//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/JC_Express/NewInputSystem_Template/ControlMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlMap"",
    ""maps"": [
        {
            ""name"": ""PlayerInput"",
            ""id"": ""5817de3f-064b-4d9e-8120-cc5ccfb40ddf"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""46884a52-6acb-4025-b136-a743d0a4b760"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c95b4513-e61b-4bdd-937e-0e6d0de3215a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1135c4ad-23af-4826-b715-ce0c9be0ceeb"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a725d732-b761-48a9-97f3-377ff2303eb7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""43021451-ba3f-40d4-9e7c-955c81219411"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""104a37da-bf59-4fdf-80a9-59b6bd491b3b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Petroller"",
            ""id"": ""a4a41900-a733-48cd-8889-72838548932a"",
            ""actions"": [
                {
                    ""name"": ""Pull"",
                    ""type"": ""Value"",
                    ""id"": ""d0da2ba3-b422-4ad2-882d-c9b8146b0e93"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""VerticalPress"",
                    ""type"": ""Button"",
                    ""id"": ""161fdf33-2889-49b6-882a-26226d5bf8a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HorizontalPress"",
                    ""type"": ""Button"",
                    ""id"": ""95f10703-6eaf-4a08-ad7a-90761a6e75a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pos"",
                    ""type"": ""Value"",
                    ""id"": ""198cd316-34bf-4e03-a086-05e61718ac70"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rot"",
                    ""type"": ""Value"",
                    ""id"": ""25085b45-5e54-4598-8278-bce7941a7e78"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeviceVelocity"",
                    ""type"": ""Value"",
                    ""id"": ""90eacbe6-65a4-44a0-8c19-45864f0e8923"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeviceAngularVelocity"",
                    ""type"": ""Value"",
                    ""id"": ""fc7fe55f-386d-4bda-81ed-8637ed9b5f71"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeviceAcceleration"",
                    ""type"": ""Value"",
                    ""id"": ""237bbc40-d2e9-4b3d-9a6a-b5790bfc081a"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeviceAugularAcceleration"",
                    ""type"": ""Value"",
                    ""id"": ""5ef3ca71-6b5f-4775-b32c-276b0a1ee6e6"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2eafe30b-94b4-4976-9293-296f3f503351"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd7c72fd-bfc1-43c3-9db1-3d9105d55c88"",
                    ""path"": ""<XRController>{RightHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a709e6f-4b32-4453-a9a7-a92d3b9e5586"",
                    ""path"": ""<XRController>{RightHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3e3d842-02f7-40c6-af9a-7310c0ca9ca8"",
                    ""path"": ""<XRController>{RightHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c5a37f9-97d1-4f63-9c64-70693083a955"",
                    ""path"": ""<XRController>{RightHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f44ea030-83a8-4346-800b-9a12a1b25eb6"",
                    ""path"": ""<XRController>{RightHand}/deviceVelocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4274467f-1163-4801-bea9-808651b504d7"",
                    ""path"": ""<XRController>{RightHand}/deviceAngularVelocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceAngularVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4450fd98-01b6-428d-bfe9-a3111a408c60"",
                    ""path"": ""<XRController>{RightHand}/deviceAcceleration"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceAcceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ab0b91a-30ea-445f-8d1d-c0c926cc89f1"",
                    ""path"": ""<XRController>{RightHand}/deviceAngularAcceleration"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceAugularAcceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Prototype"",
            ""id"": ""89bfc611-2c5b-44b2-89e7-95148a8c8489"",
            ""actions"": [
                {
                    ""name"": ""Right_Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""11971646-e56e-4c21-982d-8fef2033129a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right_Grip"",
                    ""type"": ""Button"",
                    ""id"": ""e9b31bc8-f6bc-4388-8077-83d74cc8c6d0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LHandToggle"",
                    ""type"": ""Button"",
                    ""id"": ""4fbea772-7baf-4349-b7d6-0c716e988df7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTouchToggle"",
                    ""type"": ""Button"",
                    ""id"": ""c51459a7-e27f-4458-9959-79989e9fe568"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RHandToggle"",
                    ""type"": ""Button"",
                    ""id"": ""ea7939f3-ea19-4c7b-b28e-d39d484b4ee8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RTouchToggle"",
                    ""type"": ""Button"",
                    ""id"": ""14bc0cf7-30e1-4b45-9314-81af5923c51a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LJoystick"",
                    ""type"": ""Value"",
                    ""id"": ""ee0f1d77-81b7-43dd-8ed9-00cc3a2c44e0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RJoystick"",
                    ""type"": ""Value"",
                    ""id"": ""3e908f4e-d8ab-4aa5-a2a2-65189ffa59cd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RecordButton"",
                    ""type"": ""Button"",
                    ""id"": ""416b8150-1076-4c07-9f0f-4db042d908c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaceInfoBoard"",
                    ""type"": ""Button"",
                    ""id"": ""c7dbe4b6-44c8-4ada-bba0-ecaad32d574b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""92c0048e-4aed-4b02-b433-ae03806b12bf"",
                    ""path"": ""<XRController>{RightHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1a7a4b8-9a4a-45bf-9f12-59292460496f"",
                    ""path"": ""<XRController>{RightHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right_Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3a01947-20f5-4366-817e-e1709651fbda"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LHandToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6593515e-158f-4ba2-83ad-87e0ce9b9d7d"",
                    ""path"": ""<XRController>{LeftHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTouchToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfd6adda-e4da-4715-8fa9-7f4bd928ec4e"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RHandToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c246f28-4044-443d-97fd-7b77d7c447e3"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTouchToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""143ad251-106c-4ffa-b785-627d68f2a070"",
                    ""path"": ""<XRController>{RightHand}/primary2DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""2dde93ab-9850-4026-9031-97a2b1c8d6a2"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecordButton"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""346b1ec8-bf1f-4224-9859-7625920bd869"",
                    ""path"": ""<XRController>{LeftHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecordButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""29032b52-6a25-44d4-8d73-56fda3d8c5e3"",
                    ""path"": ""<XRController>{LeftHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecordButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""41987f4d-5ae3-463e-b272-9a8f441e68f2"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RecordButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""cd0d16c1-3f00-47b7-b122-da836b5263dc"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceInfoBoard"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""2cb267f5-edf9-4a35-9872-bfda0aa48b2f"",
                    ""path"": ""<XRController>{LeftHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceInfoBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0881e817-fd75-4a20-a4de-3a1208f0686d"",
                    ""path"": ""<XRController>{RightHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceInfoBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""72367e93-d9c2-4c9b-8da3-ca029d34e13b"",
                    ""path"": ""<XRController>{LeftHand}/primary2DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LJoystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInput
        m_PlayerInput = asset.FindActionMap("PlayerInput", throwIfNotFound: true);
        m_PlayerInput_Move = m_PlayerInput.FindAction("Move", throwIfNotFound: true);
        // Petroller
        m_Petroller = asset.FindActionMap("Petroller", throwIfNotFound: true);
        m_Petroller_Pull = m_Petroller.FindAction("Pull", throwIfNotFound: true);
        m_Petroller_VerticalPress = m_Petroller.FindAction("VerticalPress", throwIfNotFound: true);
        m_Petroller_HorizontalPress = m_Petroller.FindAction("HorizontalPress", throwIfNotFound: true);
        m_Petroller_Pos = m_Petroller.FindAction("Pos", throwIfNotFound: true);
        m_Petroller_Rot = m_Petroller.FindAction("Rot", throwIfNotFound: true);
        m_Petroller_DeviceVelocity = m_Petroller.FindAction("DeviceVelocity", throwIfNotFound: true);
        m_Petroller_DeviceAngularVelocity = m_Petroller.FindAction("DeviceAngularVelocity", throwIfNotFound: true);
        m_Petroller_DeviceAcceleration = m_Petroller.FindAction("DeviceAcceleration", throwIfNotFound: true);
        m_Petroller_DeviceAugularAcceleration = m_Petroller.FindAction("DeviceAugularAcceleration", throwIfNotFound: true);
        // Prototype
        m_Prototype = asset.FindActionMap("Prototype", throwIfNotFound: true);
        m_Prototype_Right_Trigger = m_Prototype.FindAction("Right_Trigger", throwIfNotFound: true);
        m_Prototype_Right_Grip = m_Prototype.FindAction("Right_Grip", throwIfNotFound: true);
        m_Prototype_LHandToggle = m_Prototype.FindAction("LHandToggle", throwIfNotFound: true);
        m_Prototype_LTouchToggle = m_Prototype.FindAction("LTouchToggle", throwIfNotFound: true);
        m_Prototype_RHandToggle = m_Prototype.FindAction("RHandToggle", throwIfNotFound: true);
        m_Prototype_RTouchToggle = m_Prototype.FindAction("RTouchToggle", throwIfNotFound: true);
        m_Prototype_LJoystick = m_Prototype.FindAction("LJoystick", throwIfNotFound: true);
        m_Prototype_RJoystick = m_Prototype.FindAction("RJoystick", throwIfNotFound: true);
        m_Prototype_RecordButton = m_Prototype.FindAction("RecordButton", throwIfNotFound: true);
        m_Prototype_PlaceInfoBoard = m_Prototype.FindAction("PlaceInfoBoard", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInput
    private readonly InputActionMap m_PlayerInput;
    private List<IPlayerInputActions> m_PlayerInputActionsCallbackInterfaces = new List<IPlayerInputActions>();
    private readonly InputAction m_PlayerInput_Move;
    public struct PlayerInputActions
    {
        private @ControlMap m_Wrapper;
        public PlayerInputActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerInput_Move;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IPlayerInputActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IPlayerInputActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerInputActions @PlayerInput => new PlayerInputActions(this);

    // Petroller
    private readonly InputActionMap m_Petroller;
    private List<IPetrollerActions> m_PetrollerActionsCallbackInterfaces = new List<IPetrollerActions>();
    private readonly InputAction m_Petroller_Pull;
    private readonly InputAction m_Petroller_VerticalPress;
    private readonly InputAction m_Petroller_HorizontalPress;
    private readonly InputAction m_Petroller_Pos;
    private readonly InputAction m_Petroller_Rot;
    private readonly InputAction m_Petroller_DeviceVelocity;
    private readonly InputAction m_Petroller_DeviceAngularVelocity;
    private readonly InputAction m_Petroller_DeviceAcceleration;
    private readonly InputAction m_Petroller_DeviceAugularAcceleration;
    public struct PetrollerActions
    {
        private @ControlMap m_Wrapper;
        public PetrollerActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pull => m_Wrapper.m_Petroller_Pull;
        public InputAction @VerticalPress => m_Wrapper.m_Petroller_VerticalPress;
        public InputAction @HorizontalPress => m_Wrapper.m_Petroller_HorizontalPress;
        public InputAction @Pos => m_Wrapper.m_Petroller_Pos;
        public InputAction @Rot => m_Wrapper.m_Petroller_Rot;
        public InputAction @DeviceVelocity => m_Wrapper.m_Petroller_DeviceVelocity;
        public InputAction @DeviceAngularVelocity => m_Wrapper.m_Petroller_DeviceAngularVelocity;
        public InputAction @DeviceAcceleration => m_Wrapper.m_Petroller_DeviceAcceleration;
        public InputAction @DeviceAugularAcceleration => m_Wrapper.m_Petroller_DeviceAugularAcceleration;
        public InputActionMap Get() { return m_Wrapper.m_Petroller; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PetrollerActions set) { return set.Get(); }
        public void AddCallbacks(IPetrollerActions instance)
        {
            if (instance == null || m_Wrapper.m_PetrollerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PetrollerActionsCallbackInterfaces.Add(instance);
            @Pull.started += instance.OnPull;
            @Pull.performed += instance.OnPull;
            @Pull.canceled += instance.OnPull;
            @VerticalPress.started += instance.OnVerticalPress;
            @VerticalPress.performed += instance.OnVerticalPress;
            @VerticalPress.canceled += instance.OnVerticalPress;
            @HorizontalPress.started += instance.OnHorizontalPress;
            @HorizontalPress.performed += instance.OnHorizontalPress;
            @HorizontalPress.canceled += instance.OnHorizontalPress;
            @Pos.started += instance.OnPos;
            @Pos.performed += instance.OnPos;
            @Pos.canceled += instance.OnPos;
            @Rot.started += instance.OnRot;
            @Rot.performed += instance.OnRot;
            @Rot.canceled += instance.OnRot;
            @DeviceVelocity.started += instance.OnDeviceVelocity;
            @DeviceVelocity.performed += instance.OnDeviceVelocity;
            @DeviceVelocity.canceled += instance.OnDeviceVelocity;
            @DeviceAngularVelocity.started += instance.OnDeviceAngularVelocity;
            @DeviceAngularVelocity.performed += instance.OnDeviceAngularVelocity;
            @DeviceAngularVelocity.canceled += instance.OnDeviceAngularVelocity;
            @DeviceAcceleration.started += instance.OnDeviceAcceleration;
            @DeviceAcceleration.performed += instance.OnDeviceAcceleration;
            @DeviceAcceleration.canceled += instance.OnDeviceAcceleration;
            @DeviceAugularAcceleration.started += instance.OnDeviceAugularAcceleration;
            @DeviceAugularAcceleration.performed += instance.OnDeviceAugularAcceleration;
            @DeviceAugularAcceleration.canceled += instance.OnDeviceAugularAcceleration;
        }

        private void UnregisterCallbacks(IPetrollerActions instance)
        {
            @Pull.started -= instance.OnPull;
            @Pull.performed -= instance.OnPull;
            @Pull.canceled -= instance.OnPull;
            @VerticalPress.started -= instance.OnVerticalPress;
            @VerticalPress.performed -= instance.OnVerticalPress;
            @VerticalPress.canceled -= instance.OnVerticalPress;
            @HorizontalPress.started -= instance.OnHorizontalPress;
            @HorizontalPress.performed -= instance.OnHorizontalPress;
            @HorizontalPress.canceled -= instance.OnHorizontalPress;
            @Pos.started -= instance.OnPos;
            @Pos.performed -= instance.OnPos;
            @Pos.canceled -= instance.OnPos;
            @Rot.started -= instance.OnRot;
            @Rot.performed -= instance.OnRot;
            @Rot.canceled -= instance.OnRot;
            @DeviceVelocity.started -= instance.OnDeviceVelocity;
            @DeviceVelocity.performed -= instance.OnDeviceVelocity;
            @DeviceVelocity.canceled -= instance.OnDeviceVelocity;
            @DeviceAngularVelocity.started -= instance.OnDeviceAngularVelocity;
            @DeviceAngularVelocity.performed -= instance.OnDeviceAngularVelocity;
            @DeviceAngularVelocity.canceled -= instance.OnDeviceAngularVelocity;
            @DeviceAcceleration.started -= instance.OnDeviceAcceleration;
            @DeviceAcceleration.performed -= instance.OnDeviceAcceleration;
            @DeviceAcceleration.canceled -= instance.OnDeviceAcceleration;
            @DeviceAugularAcceleration.started -= instance.OnDeviceAugularAcceleration;
            @DeviceAugularAcceleration.performed -= instance.OnDeviceAugularAcceleration;
            @DeviceAugularAcceleration.canceled -= instance.OnDeviceAugularAcceleration;
        }

        public void RemoveCallbacks(IPetrollerActions instance)
        {
            if (m_Wrapper.m_PetrollerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPetrollerActions instance)
        {
            foreach (var item in m_Wrapper.m_PetrollerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PetrollerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PetrollerActions @Petroller => new PetrollerActions(this);

    // Prototype
    private readonly InputActionMap m_Prototype;
    private List<IPrototypeActions> m_PrototypeActionsCallbackInterfaces = new List<IPrototypeActions>();
    private readonly InputAction m_Prototype_Right_Trigger;
    private readonly InputAction m_Prototype_Right_Grip;
    private readonly InputAction m_Prototype_LHandToggle;
    private readonly InputAction m_Prototype_LTouchToggle;
    private readonly InputAction m_Prototype_RHandToggle;
    private readonly InputAction m_Prototype_RTouchToggle;
    private readonly InputAction m_Prototype_LJoystick;
    private readonly InputAction m_Prototype_RJoystick;
    private readonly InputAction m_Prototype_RecordButton;
    private readonly InputAction m_Prototype_PlaceInfoBoard;
    public struct PrototypeActions
    {
        private @ControlMap m_Wrapper;
        public PrototypeActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Right_Trigger => m_Wrapper.m_Prototype_Right_Trigger;
        public InputAction @Right_Grip => m_Wrapper.m_Prototype_Right_Grip;
        public InputAction @LHandToggle => m_Wrapper.m_Prototype_LHandToggle;
        public InputAction @LTouchToggle => m_Wrapper.m_Prototype_LTouchToggle;
        public InputAction @RHandToggle => m_Wrapper.m_Prototype_RHandToggle;
        public InputAction @RTouchToggle => m_Wrapper.m_Prototype_RTouchToggle;
        public InputAction @LJoystick => m_Wrapper.m_Prototype_LJoystick;
        public InputAction @RJoystick => m_Wrapper.m_Prototype_RJoystick;
        public InputAction @RecordButton => m_Wrapper.m_Prototype_RecordButton;
        public InputAction @PlaceInfoBoard => m_Wrapper.m_Prototype_PlaceInfoBoard;
        public InputActionMap Get() { return m_Wrapper.m_Prototype; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PrototypeActions set) { return set.Get(); }
        public void AddCallbacks(IPrototypeActions instance)
        {
            if (instance == null || m_Wrapper.m_PrototypeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PrototypeActionsCallbackInterfaces.Add(instance);
            @Right_Trigger.started += instance.OnRight_Trigger;
            @Right_Trigger.performed += instance.OnRight_Trigger;
            @Right_Trigger.canceled += instance.OnRight_Trigger;
            @Right_Grip.started += instance.OnRight_Grip;
            @Right_Grip.performed += instance.OnRight_Grip;
            @Right_Grip.canceled += instance.OnRight_Grip;
            @LHandToggle.started += instance.OnLHandToggle;
            @LHandToggle.performed += instance.OnLHandToggle;
            @LHandToggle.canceled += instance.OnLHandToggle;
            @LTouchToggle.started += instance.OnLTouchToggle;
            @LTouchToggle.performed += instance.OnLTouchToggle;
            @LTouchToggle.canceled += instance.OnLTouchToggle;
            @RHandToggle.started += instance.OnRHandToggle;
            @RHandToggle.performed += instance.OnRHandToggle;
            @RHandToggle.canceled += instance.OnRHandToggle;
            @RTouchToggle.started += instance.OnRTouchToggle;
            @RTouchToggle.performed += instance.OnRTouchToggle;
            @RTouchToggle.canceled += instance.OnRTouchToggle;
            @LJoystick.started += instance.OnLJoystick;
            @LJoystick.performed += instance.OnLJoystick;
            @LJoystick.canceled += instance.OnLJoystick;
            @RJoystick.started += instance.OnRJoystick;
            @RJoystick.performed += instance.OnRJoystick;
            @RJoystick.canceled += instance.OnRJoystick;
            @RecordButton.started += instance.OnRecordButton;
            @RecordButton.performed += instance.OnRecordButton;
            @RecordButton.canceled += instance.OnRecordButton;
            @PlaceInfoBoard.started += instance.OnPlaceInfoBoard;
            @PlaceInfoBoard.performed += instance.OnPlaceInfoBoard;
            @PlaceInfoBoard.canceled += instance.OnPlaceInfoBoard;
        }

        private void UnregisterCallbacks(IPrototypeActions instance)
        {
            @Right_Trigger.started -= instance.OnRight_Trigger;
            @Right_Trigger.performed -= instance.OnRight_Trigger;
            @Right_Trigger.canceled -= instance.OnRight_Trigger;
            @Right_Grip.started -= instance.OnRight_Grip;
            @Right_Grip.performed -= instance.OnRight_Grip;
            @Right_Grip.canceled -= instance.OnRight_Grip;
            @LHandToggle.started -= instance.OnLHandToggle;
            @LHandToggle.performed -= instance.OnLHandToggle;
            @LHandToggle.canceled -= instance.OnLHandToggle;
            @LTouchToggle.started -= instance.OnLTouchToggle;
            @LTouchToggle.performed -= instance.OnLTouchToggle;
            @LTouchToggle.canceled -= instance.OnLTouchToggle;
            @RHandToggle.started -= instance.OnRHandToggle;
            @RHandToggle.performed -= instance.OnRHandToggle;
            @RHandToggle.canceled -= instance.OnRHandToggle;
            @RTouchToggle.started -= instance.OnRTouchToggle;
            @RTouchToggle.performed -= instance.OnRTouchToggle;
            @RTouchToggle.canceled -= instance.OnRTouchToggle;
            @LJoystick.started -= instance.OnLJoystick;
            @LJoystick.performed -= instance.OnLJoystick;
            @LJoystick.canceled -= instance.OnLJoystick;
            @RJoystick.started -= instance.OnRJoystick;
            @RJoystick.performed -= instance.OnRJoystick;
            @RJoystick.canceled -= instance.OnRJoystick;
            @RecordButton.started -= instance.OnRecordButton;
            @RecordButton.performed -= instance.OnRecordButton;
            @RecordButton.canceled -= instance.OnRecordButton;
            @PlaceInfoBoard.started -= instance.OnPlaceInfoBoard;
            @PlaceInfoBoard.performed -= instance.OnPlaceInfoBoard;
            @PlaceInfoBoard.canceled -= instance.OnPlaceInfoBoard;
        }

        public void RemoveCallbacks(IPrototypeActions instance)
        {
            if (m_Wrapper.m_PrototypeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPrototypeActions instance)
        {
            foreach (var item in m_Wrapper.m_PrototypeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PrototypeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PrototypeActions @Prototype => new PrototypeActions(this);
    public interface IPlayerInputActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IPetrollerActions
    {
        void OnPull(InputAction.CallbackContext context);
        void OnVerticalPress(InputAction.CallbackContext context);
        void OnHorizontalPress(InputAction.CallbackContext context);
        void OnPos(InputAction.CallbackContext context);
        void OnRot(InputAction.CallbackContext context);
        void OnDeviceVelocity(InputAction.CallbackContext context);
        void OnDeviceAngularVelocity(InputAction.CallbackContext context);
        void OnDeviceAcceleration(InputAction.CallbackContext context);
        void OnDeviceAugularAcceleration(InputAction.CallbackContext context);
    }
    public interface IPrototypeActions
    {
        void OnRight_Trigger(InputAction.CallbackContext context);
        void OnRight_Grip(InputAction.CallbackContext context);
        void OnLHandToggle(InputAction.CallbackContext context);
        void OnLTouchToggle(InputAction.CallbackContext context);
        void OnRHandToggle(InputAction.CallbackContext context);
        void OnRTouchToggle(InputAction.CallbackContext context);
        void OnLJoystick(InputAction.CallbackContext context);
        void OnRJoystick(InputAction.CallbackContext context);
        void OnRecordButton(InputAction.CallbackContext context);
        void OnPlaceInfoBoard(InputAction.CallbackContext context);
    }
}
